name: spos bare arch chroot

on: [push, pull_request]

jobs:
  chroot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: create image
        run: bash test.bash
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Starport PI
          path: custom-pi.img

