name: spos

on: [push, pull_request]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      
      - name: create image
        run: bash test.bash

