name: graviton
on: [push, pull_request]

jobs:

  toolbox:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #     - name: Set up QEMU
      #       run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd toolbox
          docker buildx build --tag faddat/toolbox --platform linux/arm64 --push --cache-from faddat/toolbox:cache --cache-to faddat/toolbox:cache --progress plain .

  base:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #     - name: Set up QEMU
      #       run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd base
          wget -N --progress=bar:force:noscroll http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz
          docker buildx build --tag faddat/sos-base --platform linux/arm64 --push --cache-from faddat/sos-base:cache --cache-to faddat/sos-base:cache --progress plain .

  sos:
    runs-on: arm64
    needs: base
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #      - name: Set up QEMU
      #        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: docker buildx build --tag faddat/sos --platform linux/arm64 --progress plain --cache-to faddat/sos:cache --cache-from faddat/sos:cache --push .

  #      - name: Compress
  #        run: xz -T $(nproc) images/sos.img

  #      - name: Upload image
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: sos
  #          path: images/sos.img.xz

  sos-full:
    needs: sos
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #      - name: Set up QEMU
      #        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd full
          ls
          bash build.sh

      - name: Compress
        run: xz -T $(nproc) full/images/sos-full.img

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: full/images/sos-full.img.xz

  c2:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #     - name: Set up QEMU
      #       run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd odroid-c2
          bash build.sh

      - name: Compress
        run: xz -T $(nproc) odroid-c2/images/c2.img

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: odroid-c2/images/c2.img.xz
